version: '3.1'

services:
  node:
    build:
      context: .
      args:
        - NODE_ENV=development
    command: ./node_modules/nodemon/bin/nodemon.js --inspect=0.0.0.0:9229 server.js --exec babel-node
    ports:
      - "80:80"
      - "9229:9229"
    volumes:
      - .:/opt/app
    environment:
      - NODE_ENV=development