version: '3.1'

services:
  node:
    restart: on-failure
    build:
      context: .
      args:
        - NODE_ENV=production
    command: yarn prod:docker
    environment:
      - NODE_ENV=production
    volumes:
      - .:/ok
