version: 2

jobs:
  build:
    working_directory: /app
    docker:
      - image: docker:17.05.0-ce
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Check docker version
          command: docker info
      - run:
          name: Build docker image
          command: |
            docker build -t galileo/js-project-boilerplate .
      - run:
          name: Login to docker engine
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run:
          name: Tag image
          command: |
            docker tag $CIRCLE_BRANCH $DOCKER_USER/$CIRCLE_PROJECT_REPONAME
      - run:
          name: Push docker image
          command: |
            docker push $DOCKER_USER/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
